const { Post } = require('../models');

const postData = [
  {
    title: 'Fullstack web development from scratch!',
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut diam quam nulla porttitor massa. Enim neque volutpat ac tincidunt vitae semper quis lectus. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Senectus et netus et malesuada. Vel turpis nunc eget lorem dolor sed viverra ipsum. Sit amet purus gravida quis blandit turpis. Suscipit tellus mauris a diam maecenas sed enim ut sem. Amet est placerat in egestas. Eget est lorem ipsum dolor. Placerat in egestas erat imperdiet sed euismod. Quisque id diam vel quam elementum. Ullamcorper morbi tincidunt ornare massa eget. Sem viverra aliquet eget sit amet. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Duis at tellus at urna condimentum mattis pellentesque id nibh.

    Viverra justo nec ultrices dui sapien eget mi proin sed. Id neque aliquam vestibulum morbi blandit cursus. Justo laoreet sit amet cursus. Tellus in hac habitasse platea. Gravida dictum fusce ut placerat. Eget dolor morbi non arcu risus quis varius quam quisque. Eget nullam non nisi est sit amet. Viverra accumsan in nisl nisi scelerisque eu ultrices. Posuere morbi leo urna molestie at elementum eu facilisis sed. Dictum varius duis at consectetur lorem donec. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Tincidunt id aliquet risus feugiat in ante metus dictum. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Enim sit amet venenatis urna cursus.
    
    Feugiat in ante metus dictum at tempor commodo ullamcorper. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Tincidunt eget nullam non nisi est sit amet facilisis. At in tellus integer feugiat scelerisque varius morbi. At urna condimentum mattis pellentesque id. Nibh praesent tristique magna sit amet purus gravida quis. Dui ut ornare lectus sit amet. Euismod in pellentesque massa placerat duis ultricies. Sed euismod nisi porta lorem mollis aliquam. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Ac tortor dignissim convallis aenean et tortor at risus. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Neque sodales ut etiam sit amet nisl purus. Sem nulla pharetra diam sit amet.
    
    Cursus sit amet dictum sit amet justo donec enim diam. Proin gravida hendrerit lectus a. Interdum consectetur libero id faucibus. Laoreet id donec ultrices tincidunt. Blandit turpis cursus in hac. Et tortor at risus viverra adipiscing at in. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Gravida cum sociis natoque penatibus et magnis. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Duis at tellus at urna condimentum mattis pellentesque id. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Etiam tempor orci eu lobortis elementum nibh tellus. Suspendisse interdum consectetur libero id. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Consectetur libero id faucibus nisl tincidunt eget. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. A erat nam at lectus urna duis convallis convallis tellus. At quis risus sed vulputate odio ut enim.
    
    Donec adipiscing tristique risus nec feugiat in fermentum posuere. Lectus proin nibh nisl condimentum id. Montes nascetur ridiculus mus mauris vitae. Lectus sit amet est placerat in. Tincidunt id aliquet risus feugiat in ante metus dictum. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Aliquet lectus proin nibh nisl condimentum. Risus nullam eget felis eget nunc lobortis mattis aliquam faucibus. Nisi porta lorem mollis aliquam. Ante in nibh mauris cursus mattis molestie. Non pulvinar neque laoreet suspendisse interdum consectetur. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Ac auctor augue mauris augue neque gravida in fermentum. Suspendisse potenti nullam ac tortor vitae. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Id cursus metus aliquam eleifend mi in nulla. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Vitae justo eget magna fermentum iaculis eu non diam. Pellentesque nec nam aliquam sem et tortor consequat id porta.`,
    author_id: 1
  },
  {
    title: 'Handlebars makes frontend development easy!',
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut diam quam nulla porttitor massa. Enim neque volutpat ac tincidunt vitae semper quis lectus. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Senectus et netus et malesuada. Vel turpis nunc eget lorem dolor sed viverra ipsum. Sit amet purus gravida quis blandit turpis. Suscipit tellus mauris a diam maecenas sed enim ut sem. Amet est placerat in egestas. Eget est lorem ipsum dolor. Placerat in egestas erat imperdiet sed euismod. Quisque id diam vel quam elementum. Ullamcorper morbi tincidunt ornare massa eget. Sem viverra aliquet eget sit amet. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Duis at tellus at urna condimentum mattis pellentesque id nibh.

    Viverra justo nec ultrices dui sapien eget mi proin sed. Id neque aliquam vestibulum morbi blandit cursus. Justo laoreet sit amet cursus. Tellus in hac habitasse platea. Gravida dictum fusce ut placerat. Eget dolor morbi non arcu risus quis varius quam quisque. Eget nullam non nisi est sit amet. Viverra accumsan in nisl nisi scelerisque eu ultrices. Posuere morbi leo urna molestie at elementum eu facilisis sed. Dictum varius duis at consectetur lorem donec. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Tincidunt id aliquet risus feugiat in ante metus dictum. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Enim sit amet venenatis urna cursus.
    
    Feugiat in ante metus dictum at tempor commodo ullamcorper. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Tincidunt eget nullam non nisi est sit amet facilisis. At in tellus integer feugiat scelerisque varius morbi. At urna condimentum mattis pellentesque id. Nibh praesent tristique magna sit amet purus gravida quis. Dui ut ornare lectus sit amet. Euismod in pellentesque massa placerat duis ultricies. Sed euismod nisi porta lorem mollis aliquam. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Ac tortor dignissim convallis aenean et tortor at risus. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Neque sodales ut etiam sit amet nisl purus. Sem nulla pharetra diam sit amet.
    
    Cursus sit amet dictum sit amet justo donec enim diam. Proin gravida hendrerit lectus a. Interdum consectetur libero id faucibus. Laoreet id donec ultrices tincidunt. Blandit turpis cursus in hac. Et tortor at risus viverra adipiscing at in. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Gravida cum sociis natoque penatibus et magnis. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Duis at tellus at urna condimentum mattis pellentesque id. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Etiam tempor orci eu lobortis elementum nibh tellus. Suspendisse interdum consectetur libero id. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Consectetur libero id faucibus nisl tincidunt eget. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. A erat nam at lectus urna duis convallis convallis tellus. At quis risus sed vulputate odio ut enim.
    
    Donec adipiscing tristique risus nec feugiat in fermentum posuere. Lectus proin nibh nisl condimentum id. Montes nascetur ridiculus mus mauris vitae. Lectus sit amet est placerat in. Tincidunt id aliquet risus feugiat in ante metus dictum. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Aliquet lectus proin nibh nisl condimentum. Risus nullam eget felis eget nunc lobortis mattis aliquam faucibus. Nisi porta lorem mollis aliquam. Ante in nibh mauris cursus mattis molestie. Non pulvinar neque laoreet suspendisse interdum consectetur. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Ac auctor augue mauris augue neque gravida in fermentum. Suspendisse potenti nullam ac tortor vitae. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Id cursus metus aliquam eleifend mi in nulla. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Vitae justo eget magna fermentum iaculis eu non diam. Pellentesque nec nam aliquam sem et tortor consequat id porta.`,
    author_id: 2
  },
];

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;